CREATE OR REPLACE PACKAGE VEHICLE_DETAILCLIENT_UTIL       /*client code to display vehicle details*/
AS
PROCEDURE VEHICLEINFO(V_Vehiclereg_id VEHICLE_DETAILS.Vehiclereg_id%TYPE);
FUNCTION USER_LOGIN_VALIDATION(V_Vehicleregid1 USERLOGIN_DETAILS.Vehiclereg_id%TYPE,V_USERID4 USERLOGIN_DETAILS.Vehiclereg_number%TYPE,V_PASSWORD4 USERLOGIN_DETAILS.User_password%TYPE) RETURN BOOLEAN;
END VEHICLE_DETAILCLIENT_UTIL;

CREATE OR REPLACE PACKAGE BODY VEHICLE_DETAILCLIENT_UTIL   /*package body for client code*/
AS
PROCEDURE VEHICLEINFO(V_Vehiclereg_id VEHICLE_DETAILS.Vehiclereg_id%TYPE)
IS
REF_VEHICLE SYS_REFCURSOR;
V_R_VEHICLE VEHICLE_INFO_SEARCH.R_VEHI_RECORD;
BEGIN
DBMS_OUTPUT.PUT_LINE('VEHICLE INFORMATION');
VEHICLE_INFO_SEARCH.VEHICLE_SEARCH_BYVEHICLEREGID(V_Vehiclereg_id,REF_VEHICLE);
LOOP
FETCH REF_VEHICLE INTO V_R_VEHICLE;
EXIT WHEN REF_VEHICLE%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('VEHICLE REGISTRATION ID:'||V_R_VEHICLE.V_Vehiclereg_id||'VEHICLE OWNER:'||V_R_VEHICLE.V_Vehicle_owner||'VEHICLE NAME:'||V_R_VEHICLE.V_Vehicle_name||'VEHICLE MODEL:'||V_R_VEHICLE.V_Vehicle_model||'FUEL NORMS:'||V_R_VEHICLE.V_Fuel_norms||'RC NUMBER:'||V_R_VEHICLE.V_Rc_number||'EMISSION EXPIRY:'||V_R_VEHICLE.V_Emission_upto_date||'INSURANCE EXPIRY:'||V_R_VEHICLE.V_Insurance_upto_date);
END LOOP;
CLOSE REF_VEHICLE;
END VEHICLEINFO;

FUNCTION USER_LOGIN_VALIDATION(V_Vehicleregid1 USERLOGIN_DETAILS.Vehiclereg_id%TYPE,V_USERID4 USERLOGIN_DETAILS.Vehiclereg_number%TYPE,V_PASSWORD4 USERLOGIN_DETAILS.User_password%TYPE) RETURN BOOLEAN
IS
V_RESULT BOOLEAN:=FALSE;
V_USERID6 USERLOGIN_DETAILS.Vehiclereg_number%TYPE;
V_USERPASSWORD6 USERLOGIN_DETAILS.User_password%TYPE;
BEGIN
SELECT Vehiclereg_number,User_password INTO V_USERID6,V_USERPASSWORD6 FROM USERLOGIN_DETAILS WHERE Vehiclereg_id=V_Vehicleregid1;
IF SQL%FOUND THEN
IF V_USERID4=V_USERID6 AND V_PASSWORD4=V_USERPASSWORD6 THEN      
V_RESULT:=TRUE;
DBMS_OUTPUT.PUT_LINE('USER LOGIN CREDENTIAL VALID');
ELSE
DBMS_OUTPUT.PUT_LINE('USER LOGIN CREDENTIAL IS INVALID');
END IF;
ELSE
DBMS_OUTPUT.PUT_LINE('USER ID AND PASSWORD NOT FOUND');
END IF;
RETURN V_RESULT;
END USER_LOGIN_VALIDATION;  




END VEHICLE_DETAILCLIENT_UTIL;  


 